### ISSUE TITLE
Image unavailable no Docker Hub

### ISSUE THREAD

**Issue by janikga** [omdv/docker-jupyter-xgboost#1]
Hey there,

I just stumbled upon this custom image you made, because I'm in need for an image that includes the `xgboost` package (which the default jupyter data science one does not have, unfortunately). When I tried to pull the image from Docker Hub, I could not be found (the same happens when I search on Docker Hub). Is there any reason for this?

**Comment by omdv** [comment]
Hi. Sorry, looks like I wrote a wrong name in README. It is called [jupyter-spark-xgboost](https://cloud.docker.com/u/omdv/repository/docker/omdv/jupyter-spark-xgboost) in Docker Hub. So you should be able to run it with:

`docker run -d -p 8888:8888 -p 6006:6006 omdv/jupyter-spark-xgboost`

**Comment by omdv** [comment]
Well, actually, first I should have asked you which one you want. There are two docker images. For some reason the only one which is published is spark one. I assume you want the other one?

**Comment by janikga** [comment]
Haha sorry, yes I'm interested in the `jupyter-datascience-xgboost` one! @omdv

**Comment by janikga** [comment]
found another solution, not needing this anymore! Cheers anyway
